// File generated by FlutterFire CLI.
// This file is the Dart configuration file for Firebase.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIwHLIHh1Iz8a3BkJbT2-cDgkP_p3hus8',
    appId: '1:293410986133:web:9bf5d6447184334839e39c',
    messagingSenderId: '293410986133',
    projectId: 'breatheasy-17e5c',
    authDomain: 'breatheasy-17e5c.firebaseapp.com',
    storageBucket: 'breatheasy-17e5c.firebasestorage.app',
    measurementId: 'G-X3G3SXC6GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB1EZ8ke2E-UcCb9gKMCQF2WpcKFgfJao',
    appId: '1:293410986133:android:598dc3728ff725dc39e39c',
    messagingSenderId: '293410986133',
    projectId: 'breatheasy-17e5c',
    storageBucket: 'breatheasy-17e5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMEDG1CtL6-akAXt23vs3IBgDcwGElU7I',
    appId: '1:293410986133:ios:07dbcba388ad2c1739e39c',
    messagingSenderId: '293410986133',
    projectId: 'breatheasy-17e5c',
    storageBucket: 'breatheasy-17e5c.firebasestorage.app',
    iosBundleId: 'com.breatheasy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMEDG1CtL6-akAXt23vs3IBgDcwGElU7I',
    appId: '1:293410986133:ios:07dbcba388ad2c1739e39c',
    messagingSenderId: '293410986133',
    projectId: 'breatheasy-17e5c',
    storageBucket: 'breatheasy-17e5c.firebasestorage.app',
    iosBundleId: 'com.breatheasy.app',
  );
}
